### ISSUE TITLE
libX11.diff missing

### ISSUE THREAD

**Issue by Schmackbolzen** [pelya/xserver-xsdl#101]
If you follow the build instructions from https://github.com/pelya/commandergenius/tree/sdl_android/project/jni/application/xserver then build.sh will be stopping at "patch -p0 < ../../libX11.diff || exit 1" in line 411 due to the diff file missing. Seems like it was forgotten to be added when committing.

**Comment by Questandachievement7Developer** [comment]
Im also stuck at 
im also using android NDK r19 due 
to r11c missing clang wrapper

libX11-1.6.7/x11.pc.in
+ cd libX11-1.6.7
../build.sh: 411: ../build.sh: cannot open ../../libX11.diff: No such file
+ patch -p0
+ exit 1

**Comment by Questandachievement7Developer** [comment]
Hello again it is fixed by writing libX11.diff manually

write the libX11.diff on {your_project_Folder}/project/jni/application/xserver/xserver/android


--- configure.ac
+++ configure.ac
@@ -1,7 +1,7 @@

 # Initialize Autoconf
 AC_PREREQ([2.60])
-AC_INIT([libX11], [1.6.6],
+AC_INIT([libX11], [1.6.7],
         [https://gitlab.freedesktop.org/xorg/lib/libx11/issues], [libX11])
 AC_CONFIG_SRCDIR([Makefile.am])
 AC_CONFIG_HEADERS([src/config.h include/X11/XlibConf.h])


and when you are prompted just press y

however after that fixed there is another problem there is undefined refrence to 'wctomb' 'mblen'
and there is clang error : linker command

**Comment by pelya** [comment]
Please copy libX11.diff from source archive:
https://sourceforge.net/projects/libsdl-android/files/apk/XServer-XSDL/
I will fix Git repo this week.

**Comment by pelya** [comment]
Fixed
