### ISSUE TITLE
Better wacom pen events

### ISSUE THREAD

**Issue by cbm755** [pelya/xserver-xsdl#14]
I have a Samsung Note 8.  I'd like to run Xournal (awesome for annotating pdf files and handwritten notes) from my GNU/Linux chroot.

I find the pen events that get through xserver-xsdl are a bit poor, certainly not good enough for handwriting.  It is possible to improve this somehow?

I don't know enough about android's input system but the best case would be letting my chroot get the raw xinput events.

Currently, the "sample rate" is too low (a curve becomes very jagged, unless drawn very slowly).

Just for info, "Quill", a native Android app does a bit better with handwriting so I guess the raw input is somehow available (although I'm still not sure its as good as the Samsung apps which came with my device---now long gone).

Sorry if this is not specific enough, and I should probably test your gimp packages before complaining but I wanted to at least have the bug reported for now.

**Comment by pelya** [comment]
Yes, please try Gimp - it processes all input events, whereas other apps,
like XSDL or Debian noroot, process only the last touch event for the video
frame, which improves redraw speed, because Note devices send a lot of
touch events, like 5-10 per one video frame.
I've tried xournal, and it seems like xournal itself skips events, because
drawing curved lines it works better in Gimp. You can do that right inside
Gimp app - open root terminal, and type
apt-get update
apt-get install xournal

**Comment by cbm755** [comment]
Thanks!  I have now played with xournal within your gimp/inkscape debian install.  More recent git works much better**.

Questions (and please let me know if you'd like these in three separate bugs!)

1)  Can you expose/make configurable the Xsdl app to receive all events like the one in Gimp/Inkscape app?

2)  I notice the events, even in Gimp's input dialog are just "Core Pointer" (touch screen) and "Generic Pointer" (the pen, I think, b/c it has a "pressure" axis).  On my Thinkpad X230 Tablet (real GNU/Linux, not Android), I have "Wacom ISDv4 E6 Finger touch" and "Wacom ISDv4 E6 Pen stylus", etc.  Recent Xournal uses these names, for example, to allow finger scrolling but pen drawing (which is rather nice).  I think I can hack around it in the Xournal source but just wondering if proper xinput names are available from Android, and if so can you pass them through to the X server?

3)  Finally, I don't know if the note8 wacom pen has "tilt" like the Thinkpad one, but this would be a nice thing to expose in your gimp/inkscape app (i.e., for users doing calligraphy).  Actually, don't really know if the thinkpad one really has tilt, but Gimp "Input Devices" dialog claims it does.  I could test this if you care...

*\* For anyone reading this trying to get decent Xournal running on Android: what works for me is the "next" branch of https://github.com/dmgerman/xournal. The gtk3 branch works even worse than whatever old version is in Debian, which (as Pelya says) works quite poorly on note8.

**Comment by cbm755** [comment]
Here's a screenshot of inputs in Gimp on GNU/Linux:

![gimp_thinkpad_x230t_input_devices](https://cloud.githubusercontent.com/assets/818622/3153542/dfc703ac-ea9c-11e3-8f0a-09851459cedf.png)

**Comment by cbm755** [comment]
I put some notes on xournal on [https://github.com/dmgerman/xournal/wiki/Xournal-on-Android-via-GNU-Linux-chroot] in case thatis of interest, including screenshots of what results I can get using the Gimp/Inkscape app.

**Comment by pelya** [comment]
I'll make #1 a user-configurable option.

I still think that even with this option XSDL does not send all touch
events, because lines in Samsung note taking app are more smooth than in
Gimp, it may however be because Gimp does not convert line segments to
curves, as Samsung app does. So I'll have to create some kind of test app
to check that.

I'll look how to change #2 tomorrow.

My Note 3 does not support pen tilt, you may test it on your device by
installing this app:
https://play.google.com/store/apps/details?id=com.input.events.logger.debug.app

I put some notes on xournal on [
https://github.com/dmgerman/xournal/wiki/Xournal-on-Android-via-GNU-Linux-chroot]
in case thatis of interest, including screenshots of what results I can get
using the Gimp/Inkscape app.

**Comment by pelya** [comment]
I've modified the mouse device name, see here:
https://github.com/pelya/xserver-xsdl/commit/3cce1acc1f943ded8491e1be814aebfce6e09023
Now it should be "Android touchscreen and stylus".
I'll update XSDL with this change in a week or two.

**Comment by cbm755** [comment]
Thanks!  I haven't tested but I'm not confident this changes much:

1)  Should it not depend on whether there is a stylus?  

2)  The goal should be to have two separate xinput devices for touch and stylus.  I think Gimp does indeed see it this way within the Gimp/Inkscape app, but I will double-check.  Ideally, those xinput devices would be labeled (e.g., as in Gimp's "Configure Input Devices", see screenshot above on GNU/Linux).

**Comment by pelya** [comment]
1) - no. People also use stylus for generic Linux desktop usage, I guess
they won't be happy if redraw rate drops because of 3x more touch events
sent.

2) I did not understand you, now I see. I can split input into two devices,
but won't that create an issue on phones with no stylus?

BTW did you try that app, that shows raw input events? I still want to know
if your tablet supports pen tilt.
https://play.google.com/store/apps/details?id=com.input.events.logger.debug.app

**Comment by cbm755** [comment]
Sorry, yes I did try it: Note 8 does not seem to have tilt sensing.

**Comment by pelya** [comment]
BTW your S Pen has a button, which will send right mouse click to the X
clients, maybe you can reuse it to scroll Xournal.

Can you use the other part of S Pen as an eraser? I read that in some news,
probably was some fake rumor.

**Comment by cbm755** [comment]
Sorry, confusing multiple issues here.  Regarding 1): what I meant to say is should the name be "Android touchscreen" by default.  Then if there physically is a stylus, name it "Android touchscreen and stylus".

Ditto re: "Creating an issue on phones with no stylus".  If there is no stylus, it should not be presented.

Surely ideal situation is all inputs devices connected to the Android OS are passed through to the SDL app?  So if someone connects a usb hub and plugs in 3 mice and 2 keyboards..., then those are accessibly as they would be in standard (non-android) GNU/Linux distro

Re: right-click: probably!  But I haven't tried.  I don't believe it has a eraser button.  But the pen from my thinkpad does and it works on the Note 8...

**Comment by pelya** [comment]
I've finally tested sub-frame touch events feature on my Note 3, I confirmed that XSDL does not lose or drop any events. Samsung's paint tool just applies something like Bezier curve to the drawn line, unlike Gimp/Xournal, that's why it looks smoother.
I've also made this option user-configurable in XSDL 1.11.15, you can enable it in "Change device config" menu, in Mouse emulation -> Advanced. I'll publish 1.11.15 soon.
The touch input device will stay named as "Android touchscreen and stylus" for now, there are no separate touch devices for finger/stylus yet.
