### ISSUE TITLE
Connect to localhost

### ISSUE THREAD

**Issue by blindpenguin** [pelya/xserver-xsdl#15]
Hi,

is it possible to set the default address to localhost/127.0.0.1?

I don't want to reset the ip env setting on chroot everytime i'm moving...

**Comment by pelya** [comment]
XSDL accepts connections from amywhere, even from outside of your network.
You may just specify DISPLAY=:0 for your chroot environment, it will use
Unix socket.

**Comment by blindpenguin** [comment]
Ah, this works. Thank you. :)

**Comment by pelya** [comment]
For best results, download this library to your chroot:
https://github.com/pelya/cuntubuntu/blob/master/dist/libandroid-shmem.so?raw=true
then do
export LD_PRELOAD=/path/to/libandroid-shmem.so
It will enable shared memory between XSDL and Linux apps, so they will draw
a tiny bit faster.

**Comment by ericfont** [comment]
sorry for necro bump, but I've used your libandroid-shmem.so and it seems to work for X.  But I'd like to do a similar thing with pulse audio, such that a music app inside of a LinuxDeploy archlinuxarm chroot can send the audio directly to XSDL's pulse server without having to go through 127.0.0.1.  Any ideas?  The app I'm using is MuseScore, but I'm noticing a significant delay and some choppines when playing audio.  (I was looking at https://wiki.archlinux.org/index.php/PulseAudio/Examples#PulseAudio_from_within_a_chroot_.28e.g._32-bit_chroot_in_64-bit_install.29 but I'm not sure that will work with XSDL since XSDL is just an user-level app.)
