### ISSUE TITLE
It is possible to run multitouch support on XSDL? If yes, how?

### ISSUE THREAD

**Issue by ghost** [pelya/xserver-xsdl#26]
I saw that there is option "Multiple touch events per video frame".
So, I enabled it and installed "xserver-xorg-input-multitouch".
But after that firefox, and other apps don't support multitouch.
This option is really supported? If yes, what I did wrong in configuring it?
Thank's in advance.

**Comment by pelya** [comment]
This option will not enable multitouch support for X clients, it will make
XSDL to capture bigger amount of events, so touch input will not be limited
to 1 event per video frame. This option is mainly used when drawing with
stylus.
X clients do not support multitouch anyway, you cannot enable
xserver-xorg-input-multitouch driver on Android, because it's for different
X server. On PC this driver will do the same thing as XSDL already does -
send mouse wheel events when dragging screen with two fingers, send right
mouse click when clicking screen with two fingers etc.
