### ISSUE TITLE
Keyboard support for Gemini PDA

### ISSUE THREAD

**Issue by gfkpth** [pelya/xserver-xsdl#93]
The Gemini PDA is an Android/Linux device with a built-in keyboard
 (https://www.planetcom.co.uk/?page_id=8)

As there are some issues with the native Linux (and also for simplicity of swapping between Linux and Android), I'm trying to run a Linux chroot via Linux deploy and XSDL X-server on the device. This works largely ok (XFCE has to be started manually from a ssh shell for some reason, I might open a separate issue on that later, not sure if this is an issue with Linux deploy or XSDL), but crucially the keymapping is not working quite the way it should, at least not with the German layout.

It is, working surprisingly well, however, so Umlaute (äöü) and ß work fine, but there are some annoying gaps. The missing keys I have noticed (so far) are as follows: - \ [ ]

All these keys are reached via a key-combination with the Fn key, respectively Fn+K, Fn+3, Fn+8 and Fn+9.
Apart from that, / and = are also missing, which should be Shift+7 and Shift+0 respectively.
All other keys (and Fn-combinations) seem to work fine with the keyboard configuration on the Android side of things set to German (via the keyboard app provided by Planet Computers).

There is a keyboard config for the standalone Linux version available here:
https://github.com/gemian/xkeyboard-config

I tried copying the file from symbols/planet_vndr/gemini on that GitHub into the symbols folder of XSDL x-server, but that doesn't seem to have changed anything. I also included the same file within my Linux chroot in /usr/share/X11/xkb/symbols/planet_vndr/gemini (by setting up the gemian repository in my sources.list). Neither action has solved the problem.

Any pointer of how to get the missing symbols to work would be highly appreciated, as that would make the device fully usable in chrooted Linux. I have no problem experimenting with changes to the relevant config files, my problem is that I don't know which ones they might be...

**Comment by abliss** [comment]
I also have a gemini and use a chroot. When I fired up `xev`, it seemed that pressing  `1` and pressing `Fn+1` sent the exact same x events. To wit:
```
KeyPress event, serial 31, synthetic NO, window 0x400001,                                                                                                                 
root 0x43, subw 0x0, time 159005346, (-2,152), root:(0,154),                                                                                                          
state 0x0, keycode 10 (keysym 0x31, 1), same_screen YES,                                                                                                              
XLookupString gives 1 bytes: (31) "1"                                                                                                                                 
XmbLookupString gives 1 bytes: (31) "1"                                                                                                                               
XFilterEvent returns: False                                                                              

KeyRelease event, serial 31, synthetic NO, window 0x400001,                                                                                                               
root 0x43, subw 0x0, time 159005468, (-2,152), root:(0,154),                                                                                                          
state 0x0, keycode 10 (keysym 0x31, 1), same_screen YES,                                                                                                              
XLookupString gives 1 bytes: (31) "1"                                                                                                                                 
XFilterEvent returns: False
```

Here's an excerpt from `/system/usr/kcm/Integrated_Keyboard.kcm`:
```
key 2 {
    label:                              '2'
    base:                               '2'
    shift:                              '@'
    fn:                                 '~'
}
```
The kernel doesn't seem to know anything about this Fn chording logic:
https://github.com/zevv/gemini-android-kernel-3.18/blob/680e9de95e6b83bf2c23fd47056977d707dd5a15/drivers/misc/mediatek/aw9523/aw9523_key.c#L119

 So, I'm guessing that perhaps the SDL impl is somehow intercepting key events from the kernel before they go through the android keymapping logic? And it's not doing the same thing that Android is doing (i.e. detecting the Fn chord and looking up the appropriate keycode translation). And since it isn't translating the Fn key itself into any kind of modifier known to X, there doesn't seem to be a way to fix this with the standard x keyboard tools (e.g. xmodmap). 

Perhaps SDL could translate the Fn key into something like a Super modifier?

**Comment by abliss** [comment]
A couple more observations:
* From inside the chroot, `sudo evtest /dev/input/event2` shows FN presses coming through as KEY_FN. However, without root access I can't attach. Presumably SDL can't get events directly through that filehandle, since it doesn't need root access. It must be getting them from some higher level through the android runtime?
* I noticed that the Fn-chorded symbols which are typically shifted seem to work, but those that aren't don't. For example, Fn+1 is BACKTICK and doesn't work, while Fn+2 is TILDE and does work. Similarly the Fn chords for `+ _ |` all work, but the Fn chords for `= - \` do not.  Running `xkbwatch`, I see that pressing Fn by itself doesn't show up as any modifier, but Fn+2 shows up as a flash of the SHIFT modifier. So I wonder if the android runtime is handling "Fn+2 = BACKTICK" by transmitting key codes for "SHIFT_DOWN + KEY_BACKTICK + SHIFT_UP", in some way that works in xsdl, but whatever it does for "Fn+1", because it doesn't need to synthesize the shift key, doesn't work. 
* As further evidence for the above, here's the output of `xev` when pressing Fn+2 to get a tilde. (I did NOT actually press Shift_L):
```
KeyPress event, serial 31, synthetic NO, window 0x800001,
    root 0x43, subw 0x800002, time 166216343, (45,37), root:(47,39),
    state 0x0, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes:
    XmbLookupString gives 0 bytes:
    XFilterEvent returns: False

KeyPress event, serial 31, synthetic NO, window 0x800001,
    root 0x43, subw 0x800002, time 166216345, (45,37), root:(47,39),
    state 0x1, keycode 49 (keysym 0x7e, asciitilde), same_screen YES,
    XLookupString gives 1 bytes: (7e) "~"
```

**Comment by abliss** [comment]
I discovered this suggestion: https://github.com/pelya/commandergenius/issues/40#issuecomment-69783546
I installed the input logger apk from here:   https://m.apkpure.com/input-events-logger/com.input.events.logger.debug.app/download?from=details

When pressing Fn+1 or Fn+2, I see MetaState and Modifiers as 8 (as opposed to  0 when pressing 1 or 2 without Fn). In both cases, the "unicode" value seems to do the right thing (pressing 1 shows Unicode 49; pressing Fn+1 shows Unicode 96).

**Comment by pelya** [comment]
Should be fixed in 1.20.47

**Comment by abliss** [comment]
Wonderful news, thanks!
Any chance of an ETA for the next store release, or a snapshot APK I can
sideload to test? I don't have a working NDK build env at the moment.

**Comment by pelya** [comment]
It should be available in a few minutes on Play Store
